<?php 
session_start();
$_session=array(); //RESETTA TUTTE LE VARIABILI DI SESSIONE
session_unset(); //LIBERA TUTE LE VARIABILI DI SESSIONE ALLOCATE
session_destroy(); //DISTRUGGE LA SESSIONE

header("Location:SPOTIFY.php"); //TORNA ALLA PAGINA PRINCIPALE
exit; //SI TERMINA LO SCRIPT IN MODO DA RITORNARE ALLA SCHERMATA PRINCIPALE
?>